name: CI
on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    name: Validate & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
  
      - name: Install dependencies
        run: npm ci

      - name: Build
        working-directory: apps/frontend
        run: npm run build

      - name: Test
        working-directory: apps/frontend
        run: npm run test --if-present

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Get deployment name
        id: get-deployment-name
        run: |
          deployment_name=$(echo "${{ github.ref_name }}" | tr '\/' '-' )
          echo "deployment_name=$deployment_name" >> $GITHUB_OUTPUT

      - name: Deploy
        run: |
          aws s3 sync ./apps/frontend/dist s3://${{ secrets.S3_BUCKET_NAME }}/${{ steps.get-deployment-name.outputs.deployment_name }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Branch deployed to https://${{ steps.get-deployment-name.outputs.deployment_name }}.${{ secrets.APP_BASE_DOMAIN }}
